name: Sugar Clouds
shortname: sweet-nebulae
ignore:
  - vendor/**/*
  - vendor
run: bin/hello_world
gems: rspec
version: 0.0.1
release: Mindfully
icons:
  osx: path/to/custom/App.icns
  gtk: path/to/custom/app.png
  win32: path/to/custom/App.ico
dmg:
  ds_store: path/to/custom/.DS_Store
  background: path/to/custom/background.png
custom: my custom feature
