name: Sugar Clouds
shortname: sweet-nebulae
ignore:
  - vendor/**/*
  - vendor
run: bin/hello_world
gems: rspec
version: 0.0.1
release: Mindfully
icons:
  osx: support/boots.icns
  gtk: support/boots_512x512x32.png
  win32: support/boots.ico
dmg:
  ds_store: path/to/custom/.DS_Store
  background: path/to/custom/background.png
custom: my custom feature
